baseURL = "/"
languageCode = "en-us"
title = "Further Letters and Essays"
theme = "paperesque"

[[params.menu]]
  name = "Essays...click to open"
  url = "posts/"


[[params.topmenu]]
  name = "Credits"
  url = "credits/"
